/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Token__factory } from "./Token__factory";
export { ZombieFactory__factory } from "./ZombieFactory__factory";
